// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq_uWruMQHe56FvuHsyUCdsDPkiE4WcHE',
    appId: '1:19611732310:web:d381c8ff07692f538b2ef7',
    messagingSenderId: '19611732310',
    projectId: 'bogleboogle',
    authDomain: 'bogleboogle.firebaseapp.com',
    databaseURL: 'https://bogleboogle-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bogleboogle.appspot.com',
    measurementId: 'G-8TP0KFFKW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBNt8Vb_nGJJMxeozLcPELdqcAm9frNS8',
    appId: '1:19611732310:android:486267486407e8d68b2ef7',
    messagingSenderId: '19611732310',
    projectId: 'bogleboogle',
    databaseURL: 'https://bogleboogle-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bogleboogle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNI7zfZYVDbL8uDvI76a2NmEBdDMrkZL4',
    appId: '1:19611732310:ios:bd3306b1883cc4a98b2ef7',
    messagingSenderId: '19611732310',
    projectId: 'bogleboogle',
    databaseURL: 'https://bogleboogle-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bogleboogle.appspot.com',
    iosClientId: '19611732310-msb7kq48a387fbfkvrfi6aa368on0ups.apps.googleusercontent.com',
    iosBundleId: 'com.example.boggleboogle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNI7zfZYVDbL8uDvI76a2NmEBdDMrkZL4',
    appId: '1:19611732310:ios:bd3306b1883cc4a98b2ef7',
    messagingSenderId: '19611732310',
    projectId: 'bogleboogle',
    databaseURL: 'https://bogleboogle-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bogleboogle.appspot.com',
    iosClientId: '19611732310-msb7kq48a387fbfkvrfi6aa368on0ups.apps.googleusercontent.com',
    iosBundleId: 'com.example.boggleboogle',
  );
}
